config/routes.rb
WeeklyEats::Application.routes.draw do
  resources :ingredients

  get "home/index"

  resources :meals

  resources :recipes

  resources :users

  match 'dashboard/recipes' => 'dashboard#recipes', :as => :dashboard_recipes

  root :to => 'home#index'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :recipe
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
    
    @groceries = consolidate(@meals)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meals }
    end
  end

  def consolidate(meals)
    # Find all unique names
    names = []
    meals.each do |meal|
        meal.recipe.ingredients.each do |ingredient|
             names << ingredient.name
        end
    end
    
    names.uniq!
    
    # Find quantity and recipe_id's for each name
    groceries = []
    names.each do |name|
        quantity = 0
        recipes = []
        
        meals.each do |meal|
            meal.recipe.ingredients.each do |ingredient|
                if ingredient.name == name
                    quantity += ingredient.quantity
                    recipes << ingredient.recipe_id
                end
            end
        end
        
        groceries << { 'quantity' => quantity, 'name' => name, 'recipes' => recipes.join(',') }
    end
    
    logger.info groceries
    
    groceries
end


  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render json: @meal, status: :created, location: @meal }
      else
        format.html { render action: "new" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :ok }
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %><br />
    <%= f.number_field :recipe_id %>
  </div>
  <div class="field">
    <%= f.label :completed_date %><br />
    <%= f.date_select :completed_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>Recipe</th>
    <th>Completed date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.recipe_id %></td>
    <td><%= meal.completed_date %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal', new_meal_path %>

<%= @groceries.each { |grocery| puts grocery } %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe:</b>
  <%= @meal.recipe_id %>
</p>

<p>
  <b>Completed date:</b>
  <%= @meal.completed_date %>
</p>


<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>